SyncfusionProof/SyncfusionProof/Controllers/HomeController.cs
using SyncfusionProof.Data;
using SyncfusionProof.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SyncfusionProof.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      var model = DataHelper.GetHomeModel();

      return View("Index", model);
    }

    public ActionResult About()
    {
      ViewBag.Message = "Your application description page.";

      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Your contact page.";

      return View();
    }

    public ActionResult GridCache1()
    {
      var model = DataHelper.GetHomeModel();

      return View("GridCache1", model);
    }

    public ActionResult GridCache2()
    {
      var model = DataHelper.GetHomeModel();

      return View("GridCache2", model);
    }

    public ActionResult GridEmpty()
    {
      var model = new HomeModel();

      model.Manufacturers = DataHelper.GetManufacturers();
      model.TestModels = new List<TestModel>();

      return View(model);
    }

    public ActionResult ReportModelBoundNoParameters(string customerId)
    {
      var homeModel = DataHelper.GetHomeModel();
      var testModels = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).ToList();

      return View("./DisplayTemplates/ReportModelBoundNoParametersViewer", testModels);

      //var homeModel = DataHelper.GetHomeModel();
      //var testModel = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).Single();

      //return View("./DisplayTemplates/ReportModelBoundNoParametersViewer", testModel);
    }

    public ActionResult ReportModelBoundWithParameters()
    {
      return View("./DisplayTemplates/ReportModelBoundWithParametersViewer");
    }

    public ActionResult ReportNestedModels(string customerId)
    {
      var homeModel = DataHelper.GetHomeModel();
      var testModels = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).ToList();

      return View("./DisplayTemplates/ReportNestedModelsViewer", testModels);
    }

    public ActionResult ReportMultiDataset(string customerId)
    {
      var homeModel = DataHelper.GetHomeModel();
      var testModels = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).ToList();

      return View("./DisplayTemplates/ReportMultiDatasetViewer", testModels);
    }

    public ActionResult ReportWithSubreport(string customerId)
    {
      var homeModel = DataHelper.GetHomeModel();
      var testModels = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).ToList();

      return View("./DisplayTemplates/ReportWithSubreportViewer", testModels);
    }

    public ActionResult ReportWithNestedSubreports(string customerId)
    {
      var homeModel = DataHelper.GetHomeModel();
      var testModels = homeModel.TestModels.Where(x => x.CustomerId.Equals(customerId)).ToList();

      return View("./DisplayTemplates/ReportWithNestedSubreportsViewer", testModels);
    }
  }
}

SyncfusionProof/SyncfusionProof/Controllers/ReportMultiDatasetController.cs
using Syncfusion.EJ.ReportViewer;
using System.Collections.Generic;
using System.Web.Http;

namespace SyncfusionProof.Controllers
{
  public class ReportMultiDatasetController : ApiController, IReportController
  {
    public object GetResource(string key, string resourcetype, bool isPrint)
    {
      return ReportHelper.GetResource(key, resourcetype, isPrint);
    }

    public void OnInitReportOptions(ReportViewerOptions reportOption)
    {
    }

    public void OnReportLoaded(ReportViewerOptions reportOption)
    {
    }

    public object PostReportAction(Dictionary<string, object> jsonResult)
    {
      return ReportHelper.ProcessReport(jsonResult, this);
    }
  }
}

SyncfusionProof/SyncfusionProof/Controllers/ReportNestedModelsController.cs
//this is not officially supported in syncfusion reports
//http://www.syncfusion.com/support/directtrac/incidents/149009

using Syncfusion.EJ.ReportViewer;
using System.Collections.Generic;
using System.Web.Http;

namespace SyncfusionProof.Controllers
{
  public class ReportNestedModelsController : ApiController, IReportController
  {
    public object GetResource(string key, string resourcetype, bool isPrint)
    {
      return ReportHelper.GetResource(key, resourcetype, isPrint);
    }

    public void OnInitReportOptions(ReportViewerOptions reportOption)
    {
    }

    public void OnReportLoaded(ReportViewerOptions reportOption)
    {
    }

    public object PostReportAction(Dictionary<string, object> jsonResult)
    {
      return ReportHelper.ProcessReport(jsonResult, this);
    }
  }
}

SyncfusionProof/SyncfusionProof/Controllers/ReportWithNestedSubreportsController.cs
using Syncfusion.EJ.ReportViewer;
using Syncfusion.Reports.EJ;
using SyncfusionProof.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace SyncfusionProof.Controllers
{
  public class ReportWithNestedSubreportsController : ApiController, IReportController
  {
    public object GetResource(string key, string resourcetype, bool isPrint)
    {
      return ReportHelper.GetResource(key, resourcetype, isPrint);
    }

    public void OnInitReportOptions(ReportViewerOptions reportOption)
    {
    }

    public void OnReportLoaded(ReportViewerOptions reportOption)
    {
      if (reportOption.SubReportModel != null)
      {
        //selectively load the subreport datasources based on which subreport is being loaded
        //NOTE: the subreport path is relative to the containing report, not to the root report.
        switch (reportOption.SubReportModel.ReportPath)
        {
          case "CustomerDetailsNestedOne":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "CustomerDetailsModel", "CustomerDetailsModelNestedOne"));
            break;
          case "CustomerDetailsNestedTwo":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "CustomerDetailsModel", "CustomerDetailsModelNestedTwo"));
            break;
          case "CustomerDetailsNestedThree":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "CustomerDetailsModel", "CustomerDetailsModelNestedThree"));
            break;
          case "../Shared/Address":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "AddressModel", "AddressModel"));
            break;
        }
      }
    }

    public object PostReportAction(Dictionary<string, object> jsonResult)
    {
      return ReportHelper.ProcessReport(jsonResult, this);
    }
  }
}

SyncfusionProof/SyncfusionProof/Controllers/ReportWithSubreportController.cs
using Syncfusion.EJ.ReportViewer;
using Syncfusion.Reports.EJ;
using SyncfusionProof.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace SyncfusionProof.Controllers
{
  public class ReportWithSubreportController : ApiController, IReportController
  {
    public object GetResource(string key, string resourcetype, bool isPrint)
    {
      return ReportHelper.GetResource(key, resourcetype, isPrint);
    }

    public void OnInitReportOptions(ReportViewerOptions reportOption)
    {
    }

    public void OnReportLoaded(ReportViewerOptions reportOption)
    {
      if (reportOption.SubReportModel != null)
      {
        //NOTE: Subreport DataSouces must have unique names, even if you're using multiple subreports, 
        //since the SubReportModel is just one thing, and not a collection of SubReportModels when there 
        //are multiple subreports in a single report.

        //get the data for the subreport
        reportOption.SubReportModel.DataSources.Clear();

        ////Not ideal, here, we're running a db query for every subreport involved. Slow!
        
        //var customerId = reportOption.SubReportModel.Parameters.Single(x => x.Name.Equals("CustomerId")).Values.First();
        //var customerDetailsModel = new List<CustomerDetailsModel> { DataHelper.GetTestModels(customerId).First().CustomerDetailsModel };
        
        //reportOption.SubReportModel.DataSources.Add(new ReportDataSource
        //{
        //  Name = "CustomerDetailsModel",
        //  Value = customerDetailsModel
        //});

        //This is better. We can load all the subreport data up front and extract it from the DataSources and hook it to a SubReport.

        //this one reads CustomerDetailsModel out of the TestModel data source

        ////get the TestModel
        //var testModel = ((reportOption.ReportModel.DataSources.Single(x => x.Name.Equals("TestModel")).Value as Object[]).First() as Dictionary<string, object>);

        ////extract the CustomerDetailsModel out of the TestModel as an object array
        //var customerDetailsModel = new Object[] { testModel["CustomerDetailsModel"] };

        ////intantiate the ReportDataSource for the subreport
        //var customerDetailsDataSource = new ReportDataSource("CustomerDetailsModel", customerDetailsModel);

        ////add the DataSource to the SubReportModel
        //reportOption.SubReportModel.DataSources.Add(customerDetailsDataSource);

        //this one reads the CustomerDetailsModel out of the main report's data sources at the root level

        //using the data helper instead, assuming the model we're looking for exists in base report's data sources
        //reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "CustomerDetailsModel", "CustomerDetailsModel"));

        //selectively load the subreport datasources based on which subreport is being loaded
        //NOTE: The subreport path is relative to the containing report, not to the root report.
        switch (reportOption.SubReportModel.ReportPath)
        {
          case "Subreport":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "CustomerDetailsModel", "CustomerDetailsModel"));
            break;
          case "../Shared/Address":
            reportOption.SubReportModel.DataSources.Add(ReportDataHelper.GetReportDataSource(reportOption, "AddressModel", "AddressModel"));
            break;
        }
      }
    }

    public object PostReportAction(Dictionary<string, object> jsonResult)
    {
      return ReportHelper.ProcessReport(jsonResult, this);
    }
  }
}

SyncfusionProof/SyncfusionProof/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SyncfusionProof/SyncfusionProof/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SyncfusionProof/SyncfusionProof/Views/Home/GridCache1.cshtml
@model SyncfusionProof.Data.Models.HomeModel

@{
  ViewBag.Title = "Grid Cache 1";
}

@Html.DisplayForModel("GridCaching1")

SyncfusionProof/SyncfusionProof/Views/Home/GridCache2.cshtml
@model SyncfusionProof.Data.Models.HomeModel

@{
  ViewBag.Title = "Grid Cache 2";
}

@Html.DisplayForModel("GridCaching2")

SyncfusionProof/SyncfusionProof/Views/Home/GridEmpty.cshtml
@model SyncfusionProof.Data.Models.HomeModel

@{
  ViewBag.Title = "Empty Grid";
}

<h2>Inline Editable Grid Without Data at Load Time</h2>
<ul>
  <li>Loading the grid initially full screen appears to work.</li>
  <li>Make the window smaller and add a row. The new row cannot be seen until you make the window full screen again, or refresh the page.</li>
</ul>

<div id="GridContainer">
  @Html.DisplayForModel("EmptyGrid")
</div>

@section scripts {
  <script id="Refresh" type="text/x-jsrender">
    <a href="#" class="e-toolbaricons refresh" />
  </script>
}

SyncfusionProof/SyncfusionProof/Views/Home/Index.cshtml
@model SyncfusionProof.Data.Models.HomeModel

@{
  ViewBag.Title = "Home Page";
}

@*Basic Grid*@
@*<div id="GridContainer">
  @Html.DisplayForModel("ScrollResponsiveTest")
</div>*@

@*Tabbed Grids*@
@*@Html.EJ().Tab("TabTest").Items(x =>
{
  x.Add().ID("TabOneTab").Text("Tab One").ContentTemplate(@<div class="row">@Html.DisplayForModel("TabOne")</div>);
  x.Add().ID("TabTwoTab").Text("Tab Two").ContentTemplate(@<div class="row">@Html.DisplayForModel("TabTwo")</div>);
  x.Add().ID("InlineEditingTab").Text("Inline Editing").ContentTemplate(@<div class="row">@Html.DisplayForModel("InlineEditing")</div>);
}).EnablePersistence().ClientSideEvents(x => x.ItemActive("onItemActive"))*@

@*Enable Persistence*@
@*@Html.DisplayForModel("EnablePersistence")*@

@*Multi-Select*@
@*@Html.DisplayForModel("MultiSelect")*@

@*Multi-Select Grouped*@
@*@Html.DisplayForModel("MultiSelectGrouped")*@

@*Inline Editable Grid*@
@*@Html.DisplayForModel("InlineEditing")*@

@*ListView bound to a view model*@
@*@Html.DisplayForModel("ListViewModelBinding")*@

@*ListView done manually*@
@*@Html.Partial("./DisplayTemplates/ListViewManual")*@

@*Grids that share Ids demonstrate some layout and caching problems*@
@*<ul>
  <li>@Html.ActionLink("GridCache1", "GridCache1", "Home")</li>
  <li>@Html.ActionLink("GridCache2", "GridCache2", "Home")</li>
</ul>*@

@* Toolbar Template Grid *@
@*@Html.DisplayForModel("ToolbarTemplate")*@

@* Checkbox Column Test *@
@*@Html.DisplayForModel("CheckboxColumn")*@

@*Bootstrap Tabs*@
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#tabone">Tab One</a></li>
  <li><a data-toggle="tab" href="#tabtwo">Tab Two</a></li>
  <li><a data-toggle="tab" href="#tabthree">Tab Three</a></li>
</ul>

<div class="tab-content">
  <div id="tabone" role="tabpanel" class="tab-pane fade in active">@Html.DisplayForModel("TabOne")</div>
  <div id="tabtwo" role="tabpanel" class="tab-pane fade">@Html.DisplayForModel("TabTwo")</div>
  <div id="tabthree" role="tabpanel" class="tab-pane fade">@Html.DisplayForModel("InlineEditing")</div>
</div>

@*upload box*@
@*<div class="file-upload-control">
  @(Html.EJ().Uploadbox("attachment")
  .AllowDragAndDrop(true)
  .ExtensionsDeny(".exe,.vbs,.wsh")
  .AutoUpload(true)
  .UploadBoxDialogAction(x => x.CloseOnComplete(true))
  .FileSize(524288000)
  .ClientSideEvents(x =>
    {
      x.Success("success");
      x.Error("error");
    })
    .SaveUrl("Upload")
  )
</div>*@

@*report buttons*@
@Html.ActionLink("Report Model Bound (no parameters)", "ReportModelBoundNoParameters", "Home", new { @customerId = "5423115657865424ABCD" }, new { @class = "btn btn-default" })
@Html.ActionLink("Report Model Bound (with parameters)", "ReportModelBoundWithParameters", "Home", null, new { @class = "btn btn-default" })

@*this is not officially supported in syncfusion reports*@
@*http://www.syncfusion.com/support/directtrac/incidents/149009*@
@*@Html.ActionLink("Report Nested Models", "ReportNestedModels", "Home", new { @customerId = "5423115657865424ABCD" }, new { @class = "btn btn-default" })*@

@Html.ActionLink("Report Multi Dataset", "ReportMultiDataset", "Home", new { @customerId = "5423115657865424ABCD" }, new { @class = "btn btn-default" })
@Html.ActionLink("Report With Subreport", "ReportWithSubreport", "Home", new { @customerId = "5423115657865424ABCD" }, new { @class = "btn btn-default" })
@Html.ActionLink("Report With Nested Subreports", "ReportWithNestedSubreports", "Home", new { @customerId = "5423115657865424ABCD" }, new { @class = "btn btn-default" })

@section scripts {
  <script id="Refresh" type="text/x-jsrender">
    <a href="#" class="e-toolbaricons refresh" />
  </script>
}